version: '3.8'

services:
  # MySQL Database
  mysql:
    image: mysql:8.0
    container_name: washflow_mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: washflow
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./sql:/docker-entrypoint-initdb.d
    networks:
      - washflow_network
    command: --default-authentication-plugin=mysql_native_password
    
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-proot"]
      interval: 5s
      timeout: 10s
      retries: 5
      start_period: 20s

  # phpMyAdmin 
  phpmyadmin:
    image: phpmyadmin:latest
    container_name: washflow_phpmyadmin
    restart: always
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
      PMA_USER: root
      PMA_PASSWORD: root
    ports:
      - "8080:80"
    depends_on:
      mysql:
        condition: service_healthy
    networks:
      - washflow_network

  # Apache + PHP Web Server
  web:
    image: php:8.1-apache
    container_name: washflow_web
    restart: always
    ports:
      - "8000:80"
    volumes:
      - ./:/var/www/html
    depends_on:
      mysql:
        condition: service_healthy
    networks:
      - washflow_network
    # FIX: Using the Array Command Format
    command: ["bash", "-c", "docker-php-ext-install mysqli && apache2-foreground"]


volumes:
  mysql_data:

networks:
  washflow_network:
    driver: bridge


