version: '3.8'

services:
  # MySQL Database
  mysql:
    image: mysql:8.0
    container_name: washflow_mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: washflow
      MYSQL_USER: root
      MYSQL_PASSWORD: root
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./sql:/docker-entrypoint-initdb.d
    networks:
      - washflow_network
    command: --default-authentication-plugin=mysql_native_password

  # phpMyAdmin
  phpmyadmin:
    image: phpmyadmin:latest
    container_name: washflow_phpmyadmin
    restart: always
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
      PMA_USER: root
      PMA_PASSWORD: root
      UPLOAD_LIMIT: 50M
    ports:
      - "8080:80"
    depends_on:
      - mysql
    networks:
      - washflow_network

  # Apache + PHP
  web:
    image: php:8.1-apache
    container_name: washflow_web
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./:/var/www/html
    depends_on:
      - mysql
    networks:
      - washflow_network
    command: >
      bash -c "
      docker-php-ext-install mysqli &&
      apache2-foreground
      "

volumes:
  mysql_data:

networks:
  washflow_network:
    driver: bridge

